name = "marginis"
defaultTargets = ["Marginis"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

# [[require]]
# name = "kolmogorov_extension4"
# git = "https://github.com/sgouezel/kolmogorov_extension4"

[[lean_lib]]
name = "Marginis"
